### ISSUE TITLE
Migrate API v2 endpoints

### ISSUE THREAD

**Issue by franzns** [balancer/backend#9]
Following endpoints are available on api.balancer.fi which need to be migrated:

- [x] Pools list fetching - /pools/<chainId>
    - Used by Frontend - pools table
- [x] Single pool fetching - /pools/<chainId>/poolId
    - Used by frontend - single pool page
- [x] /sor 
    - Used by Cowswap
    - Moving to beets API once SORv2 is implemented there
    - #6 
    - needs testing on all chains
- [x] /order https://github.com/balancer/beethovenx-backend/issues/10
    - Maybe Used by Cowswap? (unsure if they ever switched to it)
    - Could move to beets API eventually after SOR
    - mean finance wants to integrate
- [x] /tokens
    - Not used by any services
- [ ] /check-wallet
    - Used by the frontend to check if wallet is flagged by TRM
- [ ] /tenderly
    - Was used by SDK, No longer used?
- [ ] /hal
    - Picks up new pool creations on Ethereum/Polygon/Arbitrum/Gnosis and creates a PR to allowlist it on Frontend, and allowlist tokens in Tokenlists repo
- [ ] /defender
    - Same as /hal but works for Base and Avalanche too (so 6 chains total), both webhooks always run but they create the same PR with same details so it's ok if both run.
